[package]
name = "role_retriever"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = "2.0.13"
eyre = "0.6.12"
tokio = { version = "1.36.0", features = ["full"]}
